import {
  AngleBrackets,
  ArrowFunction,
  AtSymbol,
  BarChart,
  Binary,
  Candlestick,
  CandlestickColored,
  CircuitNode,
  Cloud,
  CodeComment,
  ComponentTag,
  CreditCard,
  CurlyBraces,
  DollarSign,
  GitBranch,
  HashSymbol,
  LaptopIcon,
  PulseWave,
  Server,
  TerminalPrompt,
  TrendingLine,
  Wallet,
} from "./icons";
import { FloatItem, SIZE_LG, SIZE_MD, SIZE_SM } from "./types";

export const SECTIONS: Record<string, FloatItem[]> = {
  hero: [
    {
      svg: <AngleBrackets />,
      position: "top-[14%] left-[6%]",
      size: SIZE_MD,
      color: "text-accent-cyan",
      opacity: "opacity-[0.18]",
      animation: "animate-float",
      delay: "0s",
    },
    {
      svg: <Candlestick />,
      position: "top-[10%] right-[12%]",
      size: SIZE_LG,
      color: "text-accent-emerald",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slow",
      delay: "1s",
      desktopOnly: true,
    },
    {
      svg: <TerminalPrompt />,
      position: "bottom-[22%] left-[14%]",
      size: SIZE_MD,
      color: "text-accent-purple",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slower",
      delay: "2s",
      desktopOnly: true,
    },
    {
      svg: <LaptopIcon />,
      position: "top-[48%] left-[3%]",
      size: SIZE_LG,
      color: "text-accent-purple",
      opacity: "opacity-[0.16]",
      animation: "animate-float",
      delay: "0.6s",
    },
    {
      svg: <CandlestickColored />,
      position: "bottom-[28%] right-[10%]",
      size: SIZE_MD,
      color: "text-accent-emerald",
      opacity: "opacity-[0.16]",
      animation: "animate-float-slow",
      delay: "1s",
      desktopOnly: true,
    },
  ],
  about: [
    {
      svg: <CurlyBraces />,
      position: "top-[5%] right-[3%]",
      size: SIZE_MD,
      color: "text-accent-cyan",
      opacity: "opacity-[0.18]",
      animation: "animate-float",
      delay: "0s",
    },
    {
      svg: <BarChart />,
      position: "bottom-[8%] left-[2%]",
      size: SIZE_LG,
      color: "text-accent-emerald",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slow",
      delay: "1.5s",
      desktopOnly: true,
    },
    {
      svg: <ArrowFunction />,
      position: "top-[40%] right-[2%]",
      size: SIZE_SM,
      color: "text-accent-purple",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slower",
      delay: "0.8s",
      desktopOnly: true,
    },
  ],
  experience: [
    {
      svg: <GitBranch />,
      position: "top-[3%] right-[3%]",
      size: SIZE_MD,
      color: "text-accent-purple",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slow",
      delay: "0.5s",
    },
    {
      svg: <CodeComment />,
      position: "bottom-[12%] left-[2%]",
      size: SIZE_MD,
      color: "text-accent-cyan",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slower",
      delay: "2s",
      desktopOnly: true,
    },
    {
      svg: <TrendingLine />,
      position: "top-[50%] right-[2%]",
      size: SIZE_SM,
      color: "text-accent-emerald",
      opacity: "opacity-[0.12]",
      animation: "animate-float",
      delay: "1s",
      desktopOnly: true,
    },
  ],
  projects: [
    {
      svg: <ComponentTag />,
      position: "top-[3%] right-[3%]",
      size: SIZE_MD,
      color: "text-accent-purple",
      opacity: "opacity-[0.12]",
      animation: "animate-float",
      delay: "0s",
    },
    {
      svg: <Candlestick />,
      position: "bottom-[5%] left-[3%]",
      size: SIZE_SM,
      color: "text-accent-cyan",
      opacity: "opacity-[0.18]",
      animation: "animate-float-slow",
      delay: "1.5s",
      desktopOnly: true,
    },
  ],
  skills: [
    {
      svg: <Binary />,
      position: "top-[4%] right-[3%]",
      size: SIZE_MD,
      color: "text-accent-cyan",
      opacity: "opacity-[0.18]",
      animation: "animate-float",
      delay: "0s",
    },
    {
      svg: <CircuitNode />,
      position: "bottom-[8%] left-[3%]",
      size: SIZE_LG,
      color: "text-accent-emerald",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slower",
      delay: "2s",
      desktopOnly: true,
    },
    {
      svg: <HashSymbol />,
      position: "top-[45%] right-[2%]",
      size: SIZE_SM,
      color: "text-accent-purple",
      opacity: "opacity-[0.18]",
      animation: "animate-float-slow",
      delay: "1s",
      desktopOnly: true,
    },
  ],
  contact: [
    {
      svg: <AtSymbol />,
      position: "top-[5%] right-[3%]",
      size: SIZE_MD,
      color: "text-accent-cyan",
      opacity: "opacity-[0.18]",
      animation: "animate-float",
      delay: "0s",
    },
    {
      svg: <PulseWave />,
      position: "bottom-[12%] left-[2%]",
      size: SIZE_LG,
      color: "text-accent-purple",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slow",
      delay: "1.5s",
      desktopOnly: true,
    },
    {
      svg: <DollarSign />,
      position: "top-[40%] right-[4%]",
      size: SIZE_SM,
      color: "text-accent-emerald",
      opacity: "opacity-[0.12]",
      animation: "animate-float-slower",
      delay: "0.8s",
      desktopOnly: true,
    },
  ],
};

// Add development / fintech / programming-specific decorations to other sections
SECTIONS.projects.push(
  {
    svg: <LaptopIcon />,
    position: "top-[12%] left-[60%]",
    size: SIZE_MD,
    color: "text-accent-purple",
    opacity: "opacity-[0.12]",
    animation: "animate-float",
    delay: "0.6s",
    desktopOnly: true,
  },
  {
    svg: <Server />,
    position: "bottom-[6%] right-[12%]",
    size: SIZE_SM,
    color: "text-accent-cyan",
    opacity: "opacity-[0.12]",
    animation: "animate-float-slow",
    delay: "1.2s",
    desktopOnly: true,
  },
);

SECTIONS.experience.push(
  {
    svg: <Candlestick />,
    position: "top-[10%] left-[6%]",
    size: SIZE_SM,
    color: "text-accent-emerald",
    opacity: "opacity-[0.12]",
    animation: "animate-float-slow",
    delay: "0.4s",
    desktopOnly: true,
  },
  {
    svg: <Wallet />,
    position: "top-[36%] right-[6%]",
    size: SIZE_MD,
    color: "text-accent-emerald",
    opacity: "opacity-[0.12]",
    animation: "animate-float",
    delay: "1.1s",
    desktopOnly: true,
  },
  {
    svg: <CreditCard />,
    position: "bottom-[4%] left-[10%]",
    size: SIZE_SM,
    color: "text-accent-cyan",
    opacity: "opacity-[0.12]",
    animation: "animate-float-slower",
    delay: "1.7s",
    desktopOnly: true,
  },
);

SECTIONS.skills.push({
  svg: <Cloud />,
  position: "top-[8%] left-[4%]",
  size: SIZE_MD,
  color: "text-accent-cyan",
  opacity: "opacity-[0.12]",
  animation: "animate-float-slow",
  delay: "0.8s",
  desktopOnly: true,
});
