import About from "@/components/About";
import Banner from "@/components/Banner";
import EmailSection from "@/components/MainLayout/EmailSection";
import MainSection from "@/components/MainLayout/MainSection";
import SocialMediaSection from "@/components/MainLayout/SocialMediaSection";
import Navbar from "@/components/Navbar";
import Experience from "@/components/Experience";
import Head from "next/head";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import ParticlesBG from "@/components/Particles";
import { SpeedInsights } from "@vercel/speed-insights/next"

export default function Home() {
	return (
		<>
			<SpeedInsights />
			<Head>
				<title>Youssef Nessafe</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="w-full h-screen overflow-x-hidden overflow-y-scroll font-bodyFont bg-bodyColor dark:bg-bodyColorDark text-textLight dark:text-bodyColor scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60">
				<Navbar />
				{/* <ParticlesBG /> */}
				<div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between relative z-1">
					<SocialMediaSection />
					<MainSection>
						<Banner />
						<About />
						<Experience />
						<Projects />
						<Contact />
						<Footer />
					</MainSection>
					<EmailSection />
				</div>
			</main>
		</>
	);
}
